// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AutoComplete: typeof import('./components/Base/AutoComplete.vue')['default']
    Datepicker: typeof import('./components/WeekView/Datepicker/Datepicker.vue')['default']
    DatepickerEvents: typeof import('./components/WeekView/Datepicker/DatepickerEvents.vue')['default']
    DatepickerHeader: typeof import('./components/WeekView/Datepicker/DatepickerHeader.vue')['default']
    DatepickerNavigation: typeof import('./components/WeekView/Datepicker/DatepickerNavigation.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Logo: typeof import('./components/Base/Logo.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./components/Base/Spinner.vue')['default']
    StationAutoComplete: typeof import('./components/WeekView/StationAutoComplete.vue')['default']
  }
}

export {}
